FROM registry.cn-hangzhou.aliyuncs.com/adguardprivate/adguardprivate:base

ARG TARGETARCH
ARG TARGETOS
ARG TARGETVARIANT

COPY --chown=nobody:nogroup\
	./dist/AdGuardPrivate_${TARGETOS}_${TARGETARCH}/AdGuardPrivate/AdGuardPrivate \
	/opt/adguardhome/AdGuardHome

RUN chmod +x /opt/adguardhome/AdGuardHome && \
	setcap 'cap_net_bind_service=+eip' /opt/adguardhome/AdGuardHome
